# Generated by Django 5.2.4 on 2025-09-22 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_notice_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ALL', 'All Notices'), ('PLACEMENT', 'Placement'), ('DEPARTMENT_MCA', 'Department of Computer Applications'), ('DEPARTMENT_ECE', 'Department of Electronics')], max_length=50)),
                ('via_email', models.BooleanField(default=False)),
                ('via_sms', models.BooleanField(default=False)),
                ('via_whatsapp', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
