# Generated by Django 5.2.4 on 2025-10-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
